---
- hosts: 18.234.106.6
  user: root
  tasks:
  - name: create directories
    file: path="{{item}}" state=directory
    with_items:
         - /dir1
         - /dir2
         - /dir3


- hosts: 172.31.52.153
  user: root
  tasks:
  - name: create files
    file: path="{{item}}" state=touch
    with_items:
         - /dir1/file1
         - /dir2/file2
         - /dir3/file3

