---
- hosts: 34.229.186.144
  user: root
  tasks:
  - name: install apache2
    package: name=apache2 state=present
    notify:
      - start apache2
  - name: install vsftpd
    package: name=vsftpd state=present
    notify:
      - start vsftpd
  - name: deploy index.html
    copy: src=files/index.html dest=/var/www/html/index.html
    notify:
     - restart apache2

  handlers:
  - name: start apache2
    service: name=apache2 state=started
  - name: start vsftpd
    service: name=vsftpd state=started
  - name: restart apache2
    service: name=apache2 state=restarted

