---
- hosts: 34.227.89.173
  user: root
  tasks:
  - name: create directories
    file: path="{{item}}" state=directory
    with_items:
         - /dir1
         - /dir2
         - /dir3

  - name: create files
    file: path="{{item}}" state=touch
    with_items:
         - /dir1/file1
         - /dir2/file2
         - /dir3/file3
